version: 2.1
orbs:
    codecov: codecov/codecov@1.0.2
jobs:
    build:
        docker:
            - image: circleci/node:10.15

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-

            - run: npm install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies={{ checksum "package.json" }}

            - run: npm run ci-test-report
            - run: npm run ci-coverage-report
            - run: npm run codecov

            - store_test_results:
                path: test_results

            - store_artifacts:
                path: .nyc_output

            - codecov/upload:
                file: coverage.lcov

            - persist_to_workspace:
                root: ~/repo
                paths: .
    
    deploy:
        docker:
            - image: circleci/node:latest
        
            working_directory: ~/repo

            steps:
                - attach_workspace:
                    at: ~/repo
                - run:
                    name: Authenticate with npm
                    command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
                - run:
                    name: Publish package
                    command: npm publish --access public

workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
            -deploy:
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v.*/